In [1]:
import torch

In [7]:
x = torch.empty(1) 

In [8]:
print(x) #like a scalar

tensor([1.8318e+25])


In [9]:
x = torch.empty(3)

In [10]:
print(x) #like a 1d vector with 3 elements

tensor([0.0000e+00, 1.0842e-19, 9.7076e+12])


In [11]:
x = torch.empty(2,3)

In [12]:
print(x) #like a 2d matrix

tensor([[9.8091e-45, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [13]:
x = torch.empty(2,2,3) #we can put more dimensions in it

In [14]:
print(x) #like a 3d

tensor([[[9.8091e-45, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])


In [15]:
x = torch.rand(2,2)

In [16]:
print(x)

tensor([[0.3468, 0.8728],
        [0.0699, 0.2768]])


In [18]:
x = torch.zeros(2,2)

In [19]:
print(x)

tensor([[0., 0.],
        [0., 0.]])


In [20]:
x = torch.ones(2,2)

In [21]:
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [22]:
print(x.dtype)

torch.float32


In [23]:
x = torch.ones(2,2, dtype = torch.int)

In [24]:
print(x)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)


In [25]:
x = torch.ones(2,2, dtype = torch.double)

In [26]:
print(x)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [27]:
x = torch.ones(2,2, dtype = torch.float16)

In [28]:
print(x)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float16)


In [29]:
print(x.size())

torch.Size([2, 2])


In [30]:
x = torch.tensor([2.5,0.1]) #create a tensor

In [31]:
print(x)

tensor([2.5000, 0.1000])


In [36]:
x = torch.ones(2,2)
y = torch.ones(2,2)
z = x+y #element wise addition

In [37]:
print(z)

tensor([[2., 2.],
        [2., 2.]])


In [40]:
z = torch.add(x,y) #same as above

In [41]:
print(z)

tensor([[2., 2.],
        [2., 2.]])


In [42]:
y.add_(x) #in place addition
#Note: In pytorch, every function which has a trailing underscore will do an inplace operation

tensor([[2., 2.],
        [2., 2.]])

In [44]:
print(x) #x doesn't change

tensor([[1., 1.],
        [1., 1.]])


In [46]:
x = torch.tensor([2.5,0.1])

In [47]:
print(x)

tensor([2.5000, 0.1000])


In [48]:
x = torch.ones(2,2)
y = torch.ones(2,2)
z = x-y #element wise subtraction

In [49]:
print(z)

tensor([[0., 0.],
        [0., 0.]])


In [50]:
x = torch.rand(2,2)
y = torch.rand(2,2)
z = x*y

In [51]:
print(x)
print(y)
print(z) #element wise multiplication

tensor([[0.1386, 0.4173],
        [0.2808, 0.5918]])
tensor([[0.9182, 0.0030],
        [0.6624, 0.6702]])
tensor([[0.1273, 0.0013],
        [0.1860, 0.3966]])


In [52]:
z = torch.mul(x,y)

In [53]:
print(z) #element wise multiplication

tensor([[0.1273, 0.0013],
        [0.1860, 0.3966]])


In [54]:
y.mul_(x)

tensor([[0.1273, 0.0013],
        [0.1860, 0.3966]])

In [55]:
z = x/y

In [56]:
print(z)

tensor([[  1.0891, 333.8019],
        [  1.5096,   1.4921]])


In [57]:
z = torch.div(x,y)

In [58]:
print(z)

tensor([[  1.0891, 333.8019],
        [  1.5096,   1.4921]])


In [59]:
x = torch.rand(5,3)

In [60]:
print(x)

tensor([[0.7690, 0.6202, 0.3586],
        [0.8687, 0.0786, 0.3549],
        [0.0420, 0.6234, 0.4989],
        [0.9920, 0.7662, 0.6124],
        [0.0956, 0.0677, 0.2507]])


In [61]:
print(x[:,0]) #get all rows of column zero

tensor([0.7690, 0.8687, 0.0420, 0.9920, 0.0956])


In [62]:
print(x[1,:]) #get second row from all the columns

tensor([0.8687, 0.0786, 0.3549])


In [63]:
print(x[1,1])

tensor(0.0786)


In [64]:
print(x[1,1].item()) #gives the actual value

0.07855117321014404


In [65]:
x = torch.rand(4,4)

In [66]:
print(x)

tensor([[0.5296, 0.4808, 0.8465, 0.7422],
        [0.5542, 0.7624, 0.5023, 0.1082],
        [0.6158, 0.2296, 0.6719, 0.0182],
        [0.3922, 0.1166, 0.4467, 0.7953]])


In [67]:
y = x.view(16)

In [68]:
print(y) #reshape into one dimension alone

tensor([0.5296, 0.4808, 0.8465, 0.7422, 0.5542, 0.7624, 0.5023, 0.1082, 0.6158,
        0.2296, 0.6719, 0.0182, 0.3922, 0.1166, 0.4467, 0.7953])


In [71]:
y = x.view(-1,8) #if we are unsure of the other dimension we need, pytorch will automatically figure it out

In [73]:
print(y) #in this case, it's determined as 2

tensor([[0.5296, 0.4808, 0.8465, 0.7422, 0.5542, 0.7624, 0.5023, 0.1082],
        [0.6158, 0.2296, 0.6719, 0.0182, 0.3922, 0.1166, 0.4467, 0.7953]])


In [74]:
print(y.size())

torch.Size([2, 8])


In [75]:
import numpy as np

In [76]:
a = torch.ones(5)

In [77]:
b = a.numpy() #tensor to numpy array

In [78]:
print(b)

[1. 1. 1. 1. 1.]


In [79]:
print(type(b))

<class 'numpy.ndarray'>


In [80]:
#if the tensor is on the CPU and not the GPU then both objects will share the same memory location, i.e.,
#if we change one, we'll change the other

In [81]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [82]:
print(b) #numpy.ndarray b got changed due to changes in a

[2. 2. 2. 2. 2.]


In [83]:
a = np.ones(5)

In [84]:
print(a)

[1. 1. 1. 1. 1.]


In [85]:
b = torch.from_numpy(a)

In [86]:
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [90]:
a+=1

In [91]:
print(a)

[2. 2. 2. 2. 2.]


In [93]:
print(b) #tensor b got modified due to changes in a

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [94]:
#above can be prevented if cuda is available

In [95]:
#numpy can only be handled in cpu

In [96]:
x = torch.ones(5, requires_grad=True) #we are telling pytorch that we need to calculate gradients in optimization

In [97]:
print(x) #default it's False

tensor([1., 1., 1., 1., 1.], requires_grad=True)
